### ISSUE TITLE
AppKit (Mac) support

### ISSUE THREAD

**Issue by toshi0383** [AliSoftware/SwiftGen#101]
I think it'd be awesome if we add AppKit support.

I should consider what to do, but this is just an idea for now.😉

**Comment by AliSoftware** [comment]
I agree with the idea, but not sure about the implications.

Probably only affect templates (which would need to use `NSColor` instead of `UIColor`, etc) and not so much SwiftGen's own source code (which is dedicated for parsing input files like storyboards, asset catalogs and color palette files, which probably have the same format on an OS X project, we'll have to check but I guess), so that will probably be an easy enough PR to implement :+1:

**Comment by tbaranes** [comment]
+1 on this, I'd love to use `SwiftGen` in OS X app :tada:

**Comment by AliSoftware** [comment]
Took a quick look and confirms it will only be a matter of duplicating existing templates and just adjusting them for AppKit.

But as I'm not developing for AppKit and have no OS X projet, I'd be glad if someone actually using OS X projects and knowing what code they expect to just propose the templates and I'll happily merge them!

**Comment by tbaranes** [comment]
I started to play with the storyboards template, but finally, I don't have nice usage for them since we don't have any navigations on mac. For now, I think it's the less important templates, so let's find nice use case before.

@toshi0383 @AliSoftware Any suggestions?

**Comment by AliSoftware** [comment]
I think @toshi0383 would have more insight than me as I'm not an OS X developer, so idk how OS X developers use Storyboards and would prefer the template to look like :wink:

I'll merge the Images, Colors and Fonts PRs soon — Adding a note in the README could be worth it too — and then it's up to you to tell me if I should also wait for a Storyboard template before releasing a new version (if you think you'll be able to create one soon) or if you don't need it or will provide it later and can wait for a later release.

**Comment by tbaranes** [comment]
Since the OS X platform is mainly using one window and work inside, it's a lot of more limited than iOS for most of the apps (there always exception). I don't think to add the storyboard features now, but I will definitely do it if I find a use case matching the need.

These four new generators will already make a nice release and it's a first step for SwiftGen on OS X! I'm looking forward for it :)

**Comment by toshi0383** [comment]
Users can instantiate controllers by NSStoryboard's `instantiateInitialController()` or `instantiateControllerWithIdentifier(_:)` methods.
Even we don't have navigations on mac apps, I think we can simply have a wrapper around this. So at least we can provide a type-safe view loading experience to users.

For your information, we have NSWindowController along with NSViewController. After a quick look in the SDK, I found out that these two controllers are siblings, not subclasses of each other. So initialController's return type should be `AnyObject`.

@AliSoftware 
Nice labels by the way !

**Comment by AliSoftware** [comment]
> For your information, we have NSWindowController along with NSViewController. After a quick look in the SDK, I found out that these two controllers are siblings, not subclasses of each other. So initialController's return type should be AnyObject.

Ah, but can't SwiftGen detect if we are generating a subclass of `NSWindowController` vs `NSViewController` and create overloads for each type, instead of `AnyObject`?

> Nice labels by the way !
Thx 😉

**Comment by AliSoftware** [comment]
@toshi0383 @tbaranes I'm actually gonna close this issue as early Mac support is already merged with #125 #126 & #127

I invite your to continue the discussion about the storyboard template in the dedicated PR #128 😉

**Comment by toshi0383** [comment]
> @toshi0383 Ah, but can't SwiftGen detect if we are generating a subclass of NSWindowController vs NSViewController and create overloads for each type, instead of AnyObject?

Yea I guess that works too!
