### ISSUE TITLE
Xcode Run Script best practices?

### ISSUE THREAD

**Issue by AndrewSB** [AliSoftware/SwiftGen#103]
Here's my run script:

```
DOT_DIR="${PROJECT_DIR}/${PROJECT_NAME}"
CONST_DIR="$DOT_DIR""/Supporting Files/Constants"

if which /usr/local/bin/swiftgen > /dev/null; then
    /usr/local/bin/swiftgen storyboards "$DOT_DIR" --output "$CONST_DIR""/Build/Storyboards.swift"
    /usr/local/bin/swiftgen images "$DOT_DIR""/Supporting Files/Assets.xcassets" --output "$CONST_DIR""/Build/Images.swift"
    /usr/local/bin/swiftgen colors "$CONST_DIR""/colors.txt" --output "$CONST_DIR""/Build/Colors.swift"
    /usr/local/bin/swiftgen strings "$CONST_DIR""/Localizable.strings" -output "$CONST_DIR""/Build/Localizable_Strings.swift"
else
    echo "BUILD ERROR: You need to brew install swiftgen"
    exit 1
fi
```

Is that more or less what should be there?
To me it feels a little verbose... What are your thoughts on adding an opinionated subcommand to swiftgen to simplify the run script? I'd be more than happy to make the PR!

**Comment by AliSoftware** [comment]
[See the dedicated wiki page](https://github.com/AliSoftware/SwiftGen/wiki/Integrate-SwiftGen-in-an-xcodeproj).

**Comment by AliSoftware** [comment]
Woops I closed this issue because the wiki page already have a solution, but I realize it make seem like a harsh reaction. Don't hesitate to add some suggestions in the comments even if issue is closed, if you find the wiki page and commands can be improved!

But to answer your question, a dedicated and opinionated subcommand to SwiftGen wouldn't really be possible because:
 * you still have to check if SwiftGen is installed, which a SwiftGen subcommand obviously can't do
 * people not always installed SwiftGen in `/usr/local/bin` as it can be installed by other means than homebrew, and especially now that it can be installed via CocoaPods too
 * people will not always organize their file the same way and use the same options as you did in your suggested script. E.g. I personally put my constants outside `SupportedFiles`, use a `colors.xml` rather than `colors.txt`, use Base Localization so put my strings file in `Base.lproj`, etc

SwiftGen is so configurable that it seems not that useful to have an opinionated command to rule them all, and it wouldn't  make sense to have a subcommand to test it own presence either, so I don't feel that would make any sense to propose that.
