### ISSUE TITLE
Optionally limit storyboard generation

### ISSUE THREAD

**Issue by Sidetalker** [AliSoftware/SwiftGen#105]
I'm using SwiftGen in a Objective-C / Swift project. The project is several years old and is 99% Objective-C code at the moment. Files are added to the Objective-C bridging header as needed, not in bulk. It would be nice if SwiftGen had the ability to read the bridging header and only create class-specific enums for classes that are imported.

**Comment by AliSoftware** [comment]
That seems like a nice idea but a complicated issue to implement, since reading the bridging header means knowing where it is but also knowing the Xcode build settings and Header Search Path to ensure the path of each file referenced (especially in case multiple files exists with the same name in different locations — I have that case in white-labeled apps for example), then read each header file to parse which ViewController classes are included in each (nothing forbids you to name your header file differently from the class name nor to have multiple VC classes in one header file, etc).

This also would require for SwiftGen to follow any transitive header inclusions (Bridging header including VC1.h which in turn includes VC2.h which includes VC3.h…) so you can see how complex it would become very quickly to implement that.

---

So this feature seems really not worth implementing at least not in this way.
But you could instead imagine separating all your storyboards accessed via Swift in a dedicated subfolder and ask SwiftGen to parse that subfolder instead of the whole project folder (that might even work if you use only symlinks I think).

Or you could propose a PR to allow a whitelist or blacklist pattern to be passed as argument to SwiftGen and filter the parsed file against those.
Or maybe we can somehow indicate that in the storyboard file itself, eg looking if the swift module associated with the VC class is not empty or whatnot (have to check if that's the case)

---

I'm closing this issue as I know I won't implement the feature you're requesting (parsing the bridging header, too much implications, would need an AST include-tree builder) — and letting it open would let people expect it to be implemented one day — but feel free to open a PR to cover an alternative solution like the ones suggested above if you find one that suits you.l, as there are other ways to limit the storyboards being parsed anyway.

**Comment by Sidetalker** [comment]
Thanks for addressing this so quickly! I hadn't considered all of the complications this method would introduce and appreciate you pointing them out for me. Those are some great suggestions for alternative solutions, I'll definitely submit a PR if I end up going one of those routes.
