### ISSUE TITLE
Do you have a timeline for next milestones?

### ISSUE THREAD

**Issue by AFcgi** [AliSoftware/SwiftGen#119]
Hey, do you have any timeline for the next milestone releases? I saw that many interesting features come up with 1.0.0.

**Comment by AliSoftware** [comment]
Yes, I'm very guilty and ashamed that I haven't have much time in the last two month to work on SwiftGen and accept all the great Pull Requests and triage all the issues pending since some time now, and I'm very very sorry for keeping you guys waiting for so long.

But fear not, SwiftGen is very much alive, in fact I really hope to have some more time this week-end and next week to finally go back to work on it and make things move forward again, so I can at last accept all those pending PRs and release a new version very soon!

Sorry again for the wait 😉

**Comment by AliSoftware** [comment]
I've updated the 1.0.0 milestone date to sunday one week from now (I hope I'll have time to release a version this week-end but don't want to make too much promises so better fix it for the week after that), so will close this issue now. Thanks!
