### ISSUE TITLE
TestHelper.diff improvements

### ISSUE THREAD

**Issue by phatblat** [AliSoftware/SwiftGen#133]
Moving discussion from [#129](https://github.com/AliSoftware/SwiftGen/pull/129#issuecomment-223789102) about the fabulous `TestHelper.diff` ✨

## Foreground Text Color

Can the foreground color be controlled?

![swiftgendifferror](https://cloud.githubusercontent.com/assets/28851/15807105/77b22c8a-2b11-11e6-8178-d55444056b01.png)

It's hard to read the black on dark red at line 37. Can the text color be changed to white?

## Callout Content

The callout from the Issue Navigator is not scrollable, so a [diff of a template with many lines](http://b.log-g.co/gMjC/image.png) gets cut off depending on the height of the screen. Less of the content is visible when the [left pane width is smaller](http://b.log-g.co/gMSh/image.png). (I can only see 47-67 lines on a 12" screen at 2048x1280)

Would it be possible to limit the visible content to the metadata (failed..., >>>>> result, etc), the mismatched line plus a configurable amount of context lines before and after the mismatch?

**Comment by phatblat** [comment]
Just noticed that the callout content is echoed to the console, where it reads fine with the "Dusk" theme.

![screen shot 2016-06-05 at 12 20 42 pm](https://cloud.githubusercontent.com/assets/28851/15807307/fc7d49f8-2b17-11e6-8788-6249bc199099.png)

However, it has the same readability issue with the Standard theme.

![screen shot 2016-06-05 at 12 22 01 pm](https://cloud.githubusercontent.com/assets/28851/15807315/264eb6f4-2b18-11e6-81de-2d9dff41b1ee.png)

**Comment by AliSoftware** [comment]
The color of the line can indeed be changed very easily.
You just have to edit [TestHelper.swift, line 13](https://github.com/AliSoftware/SwiftGen/blob/master/UnitTests/TestsHelper.swift#L13) to add some foreground color to the `code` color for the `koCode`, for example `+ colorCode("fg255,255,255")`

---

As for the callout content, I once had a version of the script only printing some context lines instead of everything. I removed the limitation because at that time the `TestHelper` was not so cleanly formatted and it was hard to locate the code easily. Now that it's much better, it might be time to re-introduce that context limitation to only print 3-4 lines around the mismatching line.

Picking only an `ArraySlice` of `lhsLines` (rest. `rhsLines`) , e.g. `lhsLines[badLineIdx-3...badLineIdx+3]` should do the trick… minor some bounds checking to ensure the indexes are not before 0 or after count.

**Comment by phatblat** [comment]
💖 

![screen shot 2016-06-08 at 8 50 58 pm](https://cloud.githubusercontent.com/assets/28851/15917544/f0a89e70-2dba-11e6-851a-6a12ec1720d5.png)
