### ISSUE TITLE
Strings: Invalid number of params

### ISSUE THREAD

**Issue by iPili85** [AliSoftware/SwiftGen#154]
My Localizable.string contains a string with the following format:

`"00001" = "Purchase of %5$@ %6$@ on %4$@ with your card ending in %2$@";`

so, the enum case generated by swiftgen looks like:
`case _00001(Any, String, Any, String, String, String)` 
and it should be like:  `case _00001(String, String, String, String)`

Is there a way to ignore swiftgen generate strings containing specific chars in its key, or to make swiftgen generate the correct number of params?

**Comment by AliSoftware** [comment]
I'm not sur why you consider the generated enum to be invalid here.

That has nothing to do with the fact that it contains specific chats in its keys. The number of parameters is totally correct, because you use positional parameters up to position 6 (in case you didn't know, `%6$@` meaning "format the 6th parameter as a String" in `printf`-like formats used by `String(format:)` and the likes)

Clearly given how you use positional parameters in your localized string, using positions 5, 6, 4, and 2 but not 1 and 3, even without SwiftGen you'll need to pass something at those positions anyway. That's exactly why SwiftGen uses `Any` here. Because your format string don't specify any placeholder for positions 1 and 3 so it can't guess what to use. That's totally intended.

Given how your Localized string is formatted, even outside of SwiftGen, you'd need to use something like this to use the format string anyway:
```
let year = "2016"
let site = "Amazon"
let amount = "200.00"
let currency = "USD"

let dummy: Any = 0
let result = String(format: "Purchase of %5$@ %6$@ on %4$@ with your card ending in %2$@", dummy, year, dummy, site, amount, currency)
```
So you see here that even without talking about SwiftGen you'll need those dummy values because your formatting string has no positional placeholder for position 1 and 3.


Maybe I can generate some warning during generation, and a different type as `Any`, but in any case I can't omit the parameter at all, as `String(format:)` expects you to pass something at position 1 and 3 anyway

The real solution to your problem is to use a proper format string which contains all positions. Because it doesn't make any sense to have a format string with no placeholder for positions in the middle anyway (SwiftGen or not). You can just change your string format to be more correct, like:
```
"00001" = "Purchase of %3$@ %4$@ on %2$@ with your card ending in %1$@";
```
This will insert the parameters into the string in the order 3, 4, 2, 1  as specified by those `x$` in your string and there wont be any missing positional parameter in your format anymore.

**Comment by AliSoftware** [comment]
For more information about positional parameters in string formats, see [this Apple documentation](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html#//apple_ref/doc/uid/TP40004265-SW1)

> Note that you can also use the “n$” positional specifiers such as %1$@ %2$s.

And [the IEEE printf specification explaining in details how they works](http://pubs.opengroup.org/onlinepubs/009695399/functions/printf.html).

> In format strings containing the "%n$" form of a conversion specification, a field width or precision may be indicated by the sequence "*m$", where m is a decimal integer in the range [1,{NL_ARGMAX}] giving the position in the argument list (after the format argument) of an integer argument containing the field width or precision, for example:

> `printf("%1$d:%2$.*3$d:%4$.*3$d\n", hour, min, precision, sec);`
