### ISSUE TITLE
%lld is converted to Int

### ISSUE THREAD

**Issue by Igor-Palaguta** [AliSoftware/SwiftGen#155]
There is no way to use swiftgen with Int64

I have string
"VIEWS_COUNT_FORMAT" = "%lld views";

and it is converted to
case VIEWS_COUNT_FORMAT(Int):

**Comment by AliSoftware** [comment]
I did this because `Int` works with all length in Swift and are already 64 bits.
_You should be able to use `L10n.VIEWS_COUNT_FORMAT(yourInt64 as Int)` or `L10n.VIEWS_COUNT_FORMAT(Int64(yourInt64))` if needs be._

It might be possible to change that behavior in SwiftGen to take the length specifier into account but I'm not sure it's worth it, given that Swift's own preferred type for integers of any size is officially `Int` and that an `Int` works with `%lld` too anyway? (many people expect to only deal with Int in Swift)

**Comment by Igor-Palaguta** [comment]
Sorry, my fault, thought swift Int is 32 bits
So no need for %lld support, for now

Thanks!
