### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by AndrewSB** [AliSoftware/SwiftGen#164]
Can we have a new release soon? Using swiftgen with the latest swift 3 beta requires a commit that has been merged into master since the last release!

**Comment by AliSoftware** [comment]
I know it has been a long time and I'm very sorry for the delay and for not having enough free time to advance on my OSS work, especially since I have urgent talks to prepare.

Because the template Stencil contexts changed with the recent PRs merged to add some features, we'll need to release a new **major** version, as it might not be fully be compatible with some old templates people might have customized.

I was planning to do that new major release some weeks ago and was ready to do so… until #160 pointed out recently that there was a problem with the new template keys in some use cases.
We can't really ship a new release with wrong template semantics — otherwise we would have to bump the major version twice in little time (once for the new buggy keys and one with the fix), and thus have to make people change their templates twice in little time, that's why I postponed that new major release until #163 came to fix this.

Now that #163 addresses the problem and stabilized the semantics for the template context keys, I plan to do that new major release as soon as I have some time to review that #163 PR, ensure tests pass, do some test run, and merge it.

**Comment by AndrewSB** [comment]
Thank you for taking the time to give such an in depth answer, I'll also take a quick look at #163, to hopefully catch anything so you can spend less time on it
