### ISSUE TITLE
Constants not generated for multiline text

### ISSUE THREAD

**Issue by mr-v** [AliSoftware/SwiftGen#187]
This seems to be\* valid way of defining multiline text in `strings` file:

```
"welcome.intro" = "Multiline intro.\
\
Many lines!";
```

`swiftgen strings` omits it and it's not available in generated file.

*It's displayed correctly in the app and Xcode highlighting picks this up.

**Comment by AliSoftware** [comment]
Indeed SwiftGen scans the strings file line by line so no wonder this doesn't work.

The fix would imply changing the parsing to use PLIST parsing instead, but given I've been quite busy the last 2 months I fear I won't have time to fix that this soon.

In the meantime you can use `Hello\nWorld` to make your multi-line text fit in one line in the Localizable.strings while still keeping the multi lines in the app, will keep you posted when I have time to fix it :wink:

**Comment by AliSoftware** [comment]
Actually if you have some time, it should not be that hard to fix yourself, if you fancy doing a PR.

This issue is basically on [these lines](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Parsers/StringsFileParser.swift#L22-L26) where I split the lines of `Localizable.strings` then iterate over each of them to build an `Entry` (representing the key, translation and detected types).

But a `Localizable.strings` is actually nothing more than a PLIST file containing a big dictionary of Strings (it's just a different format that the XML format you're used to see, but you can show it as a PLIST in Xcode if you want). So using `Dictionary(contentOfFile:)` on the file instead of splitting the lines would allow you to have a `[String:String]` that will not have the problem with the split lines you use.

Once that is changed, we still need to build the array of `Entry` from that dictionary (instead of calling `Entry.init(string)` as we do now and using the RegEx to try to separate the key from the translation), but that's not that hard, as the key and translation are already separated by the fact we would parse it as a dictionary, so that's just a matter of iterating over the dictionary's keys & values. And as for the placeholderTypes, you can use `fromTranslationString()` to build them from the dictionary's values like it's done [here](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Parsers/StringsFileParser.swift#L99)

So migrating from {splitting lines + using a regex} to {parsing as a PLIST + call `fromFormatString`} seems finally not that hard and would fix the issue. That's a good starter bug :wink
