### ISSUE TITLE
Proposal: remove default translation comments from strings template

### ISSUE THREAD

**Issue by ldiqual** [AliSoftware/SwiftGen#222]
@AliSoftware @MrAlek 

I'd like to propose something that is the total opposite of https://github.com/AliSoftware/SwiftGen/issues/58: **removing** doc comments from the strings template.

My main issue with it is that every time I modify the translation of a key, it modifies the generated strings enum. This clutters the diff and my app needs to recompile – which is a practical issue with swift as the compiler is rather slow.

The argument for *adding* translation comments in https://github.com/AliSoftware/SwiftGen/issues/58 was it was nice to command+click and see the actual default translation. I fail to see how that is useful – the key should be descriptive enough that you'd know what the string is meant for. I personally never search for a key to find out its translation because frankly it shouldn't matter what it translates to, what matter is what it describes, and that's the role of the key.

I ended up creating a template that is the exact same one that swiftgen provides, minus the comment, which prevents me from getting all the new template updates. What I would propose is to either remove the comment altogether, or at the very least make it opt-in.

How does that sound? Thanks!

**Comment by MrAlek** [comment]
Personally I like having the comments there as reference since it's a bit of a pain to look up the corresponding key in the strings files manually, but my workflow is different as well. I rarely change any strings after I've implemented them in the app.

I can understand your recompiling pain, but isn't that an effect of incremental compilation temporarily being broken in Xcode 8.1? The entire app shouldn't have to recompile because of a documentation change in one file, this is noted as fixed in the Xcode 8.2 beta 2 release notes.

> Xcode will not rebuild an entire target when only small changes have occurred. (28892475)

In my opinion it is valuable to have auto-generated documentation for the enum cases. It's up to @AliSoftware to decide what should be included in the default template. Either way we can both use custom templates to fit our needs.

**Comment by AliSoftware** [comment]
I prefer having comments as well but can understand your need. If you want we could include your template as `strings-no-comments.stencil` in the next release. It will not be the default one but you'll be able to use `-t no-comments` at least.

**Comment by ldiqual** [comment]
@MrAlek @AliSoftware Thanks for following up! I think having an extra official template without comments is a good compromise here. I'm gonna go ahead and PR it. Thanks again!
