### ISSUE TITLE
Support `performSegueWithIdentifier:sender` with UIStoryboard.Segue types

### ISSUE THREAD

**Issue by jakecraige** [AliSoftware/SwiftGen#37]
it would be great if I could call `performSegueWithIdentifier` with the segue enum type instead of having to call `rawValue`.

```swift
// this
performSegueWithIdentifier(UIStoryboard.Segue.Main.ViewAnnouncement, sender: nil)

// instead of
performSegueWithIdentifier(UIStoryboard.Segue.Main.ViewAnnouncement.rawValue, sender: nil)
```

**Comment by AliSoftware** [comment]
Good suggestion!

I'm focused on #24 which will be a big refactor that would allow people to use templates for generating the code. This will make it way easier to fix missing stuff like this in the generated code.

You could either make a PR now if this need is urgent, or wait until I introduce Stencil and the use of templates to fix the template (which would probably be way easier, but will need #24 to be done first)

**Comment by AliSoftware** [comment]
Now that #24 is fixed and that SwiftGen now uses [templates](https://github.com/AliSoftware/SwiftGen/blob/master/templates/storyboards.stencil#L57-L65), it should be very easy to make a PR to add support for this!

Probably by making the same trick with the `Segue` enum that is done with `Scene` enum, by making it conform to a `StoryboardSegue` protocol and provide an `extension StoryboardSegue where Self.RawValue == String` so that those segues can have the implementation for `performSegueWithIdentifier(…)` method for free.
