### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by esttorhe** [AliSoftware/SwiftGen#38]
Version `swiftgen` 0.5.0_1 installed with via `brew` doesn't work and throws the following error no matter what command I try :(

Tried with `Xcode 7` and `Xcode 7.1`

```console
swiftgen
[1]    72547 segmentation fault  swiftgen
```

**Comment by AliSoftware** [comment]
That's probably because it has detected your Twitter name and want to troll you :wink:

But seriously, when installed via `brew` and especially if Homebrew did pour the "bottle" (= the precompiled version of `swiftgen` directly downloaded via a `.tar.gz`) instead of compiling it on your machine locally during installation, then `swiftgen` will have a `@rpath` set to some path inside `/Applications/Xcode.app/…` so that's where it's gonna look for the Swift dylibs to load. Even if that version installed at that path is in fact Xcode 6.

I added a protection in SwiftGen's formula to only use the _bottle_ if the path `/Applications/Xcode.app` exist on your machine but didn't check that the version at that path was Xcode 7.0.1. I'll bet that's not the case for you and that's the cause of the SegFault because SwiftGen will then load Xcode 6's Swift libs instead of Xcode 7's ones, no matter what `xcode-select -p` you have.

**Comment by AliSoftware** [comment]
Could you rename your Xcode 7.0.1 to `/Applications/Xcode.app` and try again?

**Comment by esttorhe** [comment]
Oh! The twitter handle irony :joy: 

I do have a `symlink` pointing to `7.1`; don't know if that's the issue or if it should be pointing to `7.0.1` instead.

I'll try changing it anyways.

```console
Xcode.app -> /Applications/Xcode-7.1.app
```

**Comment by esttorhe** [comment]
Changing the `symlink` to `7.0.1` and «re-pouring» the bottle fixed it :beers: 

Don't know if `7.1` doesn't work for this or what ¯\\\_(ツ)\_/¯

I'm closing it. Thanks :bow:

**Comment by AliSoftware** [comment]
I don't like it. One more restriction on homebrew behavior.

I'll make a 0.5.1 that copies Swift libs over so it's independent of your Xcode install path.

**Comment by AliSoftware** [comment]
@esttorhe SwiftGen 0.5.1 just got merged into Homebrew; could you test it (with your symlink reset to 7.1 like when you had the issue) and tell if it fixed it?

Thx!

**Comment by esttorhe** [comment]
@AliSoftware just tested with the symlink back at `7.1`.

Uninstalled `swiftgen` and reinstalled via `homebrew` and is working now :ok_hand:

**Comment by AliSoftware** [comment]
:tada:
