### ISSUE TITLE
v0.6.0 breaks compilation if there are no images

### ISSUE THREAD

**Issue by jschmid** [AliSoftware/SwiftGen#41]
I know it's a edge case, but I just wanted to have it documented.

My project does not contain images yet, but I already put SwiftGen in place. 

The output file from v0.6.0 does not compile:

<img width="599" alt="screen shot 2015-10-26 at 08 41 32" src="https://cloud.githubusercontent.com/assets/574168/10723651/66cc3ab8-7bbd-11e5-997e-c2c0822cd7a4.png">

For now I put a fake image in my resources to make the ting compile.

**Comment by AliSoftware** [comment]
Mhhh that's strange because the template is supposed to [detect such cases here](https://github.com/AliSoftware/SwiftGen/blob/master/templates/images.stencil#L6), so this test must be broken somehow.

Thanks for letting me know.

**Comment by jschmid** [comment]
I guess the `images` exists, but is just empty. That's why the `if` passes.

**Comment by AliSoftware** [comment]
After investigating a bit, it appears that's actually more complicated than that and is a but in `Stencil`, which fails to convert `images` into an `[AnyObject]` — because it actually is a `[Swift.Dictionary<Swift.String, Swift.AnyObject>]` and Swift fail to convert that to `[AnyObject]`. 

I could understand why since `Swift.Dictionary` are in fact `struct` thus not `AnyObject`, but strangely, it seems to fail converting that to `[Any]` too?! (\cc @kylef)

**Comment by AliSoftware** [comment]
Now that Stencil merged my fix, this should be fixed in SwiftGen via 46fbc9c33a5b3ae81bd10f33146592e7669fe207

**Comment by jschmid** [comment]
Thanks @AliSoftware
