### ISSUE TITLE
Can't generate strings

### ISSUE THREAD

**Issue by kronik** [AliSoftware/SwiftGen#55]
I've downloaded the latest code and when I execute:

"swiftgen strings path_to_my_loc.strings" I see this:

// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import UIKit

extension UIColor {
  convenience init(rgbaValue: UInt32) {
    let red   = CGFloat((rgbaValue >> 24) & 0xff) / 255.0
    let green = CGFloat((rgbaValue >> 16) & 0xff) / 255.0
    let blue  = CGFloat((rgbaValue >>  8) & 0xff) / 255.0
    let alpha = CGFloat((rgbaValue      ) & 0xff) / 255.0

    self.init(red: red, green: green, blue: blue, alpha: alpha)
  }
}

// No color found

**Comment by AliSoftware** [comment]
Yeah it's a bug that just got reported in #54, that's because of a typo in my code making the `swiftgen string` search for the colors template instead of the strings templates. I'll try to release a fix ASAP today.

In the meantime, you can specify the full path of the right template template, using `swiftgen -p /usr/local/share/swiftgen/templates/strings-default.stencil path_to_your_loc.strings` as a workaround until I fix this properly.

**Comment by AliSoftware** [comment]
The fix is in master and tag 0.7.1.
SwiftGen 0.7.1 has been [submitted to Homebrew](https://github.com/Homebrew/homebrew/pull/45829) and is awaiting validation, shouldn't be long now.

**Comment by kronik** [comment]
Thanks!
