### ISSUE TITLE
Storyboard.swift and symbol(s) not found for architecture, only in Release

### ISSUE THREAD

**Issue by alessandroorru** [AliSoftware/SwiftGen#57]
I'm currently having an issue with generated Storyboard.swift code, but **only in release** mode. I'm using Xcode 7.1, targeting iOS 9 just for iOS.

The affected code is the call to `initialViewController()`, while using other methods works fine. 
For example in my case:
`let navigationController = UIStoryboard.Scene.Main.initialViewController() as! UINavigationController`.

Building for **archive** spits out this error:

```
Undefined symbols for architecture armv7:
  "direct type metadata for ext.MyApp.__ObjC.UIStoryboard.Scene.Main", referenced from:
      function signature specialization <Arg[0] = Dead and Owned To Guaranteed, Arg[1] = Dead and Owned To Guaranteed> of MyApp.AppDelegate.application (MyApp.AppDelegate)(__ObjC.UIApplication, didFinishLaunchingWithOptions : [__ObjC.NSObject : Swift.AnyObject]?) -> Swift.Bool in AppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't know if this is just a compiler bug due to a specific optimization flag or if it is related to swiftgen. Anyone else is having the same issue?

**Comment by AliSoftware** [comment]
Maybe related to #56 (I mean, that might be a compiler bug due to Whole Module Optimization turned on)?

**Comment by AliSoftware** [comment]
Note that in the meantime, until Apple fixes that bug, you can disable WMO in your Release build to workaround this linker bug.

**Comment by alessandroorru** [comment]
Unfortunately I didn't have WMO enabled 😕

**Comment by AliSoftware** [comment]
@alessandroorru I can't reproduce the issue on a simple project here.

Could you create a sample project to demonstrate the issue and help us reproduce?

**Comment by alessandroorru** [comment]
@AliSoftware sure!

Here is a sample project. The scheme setting is already set at "Release" also for running in simulator, so if you just press play you should see it fail. If you change it back to "Debug" it will work as expected.

Let me know if it fails also for you.. hope it helps ;)

https://www.dropbox.com/s/v4rm0w11q2x2go9/TestFailingSwiftgen.zip?dl=1

**Comment by jmacmullin** [comment]
I hit this bug too. I also did not have the whole module optimiser enabled, but just set to the default for release builds (Fast [-O]). When I disabled the optimiser, I no longer encountered the error.

**Comment by AliSoftware** [comment]
Ah thx for the feedback @jmacmullin that's definitely worth filing a dedicated radar to Apple!

**Comment by AliSoftware** [comment]
Ok so I can confirm that:
* I have the bug with @alessandroorru 's sample project when building in Release too (and not in Debug)
* This is a known LLVM issue (a engineer at Apple working on the Swift compiler confirmed it) when building with optimizations turned on
* There are two workaround possible:
  * Don't use `-O` (change this in your Build Settings of the Release configuration of your project)
  * Or don't use nested types in class extensions — which is what the default template of SwiftGen does — until Apple fixes that bug.

For the second workaround, the fix consist of generating top-level `struct UIStoryboardScene` and `struct UIStoryboardSegue` instead of declaring `struct Scene` and `struct Segue` as a nested type in `extension UIStoryboard`. The result being that you'll have to do `UIStoryboardScene.Main.initialViewController()` instead of `UIStoryboard.Scene.Main.initialViewController()`

**Comment by ryanbooker** [comment]
What names should the top level structs have? Calling them UIXXX seems risky and UIStoryboardSegue already exists, obviously.

I need this too, so I'll just fix it if no one else has. :)

**Comment by AliSoftware** [comment]
@ryanbooker One can always choose different enum names using the `--sceneEnumName` and `--segueEnumName` options, but as you point out we can't use `UIStoryboardSegue` for the default names indeed. I'd vote for `StoryboardSegue` and `StoryboardScene`
