### ISSUE TITLE
Documenting String key enum cases w/ default translation

### ISSUE THREAD

**Issue by MrAlek** [AliSoftware/SwiftGen#58]
Something that xcres has been doing for a while is to document each generated string key with the default translation for that key. That way, you can see the output string when alt-clicking the enum or using auto-complete which is really nice. Currently, the string value isn't exposed as a variable in the strings template engine.

Example input:
``` C
"confirmation_alert_title" = "Do you really want to do this action?";
"confirmation_alert_cancel_title" = "Abort";
```

Desired output:
``` Swift
enum L10n {
  /// Do you really want to do this action?
  case ConfirmationAlertTitle

  /// Abort
  case ConfirmationAlertCancelTitle
}
```

**Comment by AliSoftware** [comment]
That's an interesting addition, and should be pretty easy to add.

The only thing to change in my code is to store the translation, [which is already captured here](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Parsers/StringsFileParser.swift#L86), as an additional property in the `Entry` struct.
Then, [inject that `Entry.translation` in the Stencil's context here](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Stencil/Contexts.swift#L109-L111) in addition to the `key` and `params` keys, so that this translation can be used in the string templates.

Then using that in the default string template would be as simple as inserting `// {{ }}` [here](https://github.com/AliSoftware/SwiftGen/blob/master/templates/strings-default.stencil#L18).

It would be really nice if you could propose a PR to do those simple changes :wink:
_(dont forget to fix unit tests accordingly and credit yourself in the CHANGELOG if you do)_

**Comment by MrAlek** [comment]
Glad you like the idea :) I'll look at the code and send you a PR tomorrow!
