### ISSUE TITLE
Document how to integrate SwiftGen into .xcodeproj

### ISSUE THREAD

**Issue by mman** [AliSoftware/SwiftGen#59]
I'd like to integrate swiftgen directly into my xcode project file so that it's invoked automatically on each build so that all generated files are always up to date.

Could you please provide an example how to do it properly in README

thanks,
Martin

**Comment by AliSoftware** [comment]
Hi Martin,

This would probably be as simple [as adding a "Script Build Phase" in your target settings](https://developer.apple.com/library/ios/recipes/xcode_help-project_editor/Articles/AddingaRunScriptBuildPhase.html) which invokes the `swiftgen` commands from there. Simple as that.

---

As regard to documenting that in the README, I don't think that's the right place:
* The README is pretty big already
* This is more [a documentation related to Xcode](https://developer.apple.com/library/ios/recipes/xcode_help-project_editor/Articles/AddingaRunScriptBuildPhase.html) (that trick works for anything, not just SwiftGen)
* It could still be interesting to document, for the specific use case of SwiftGen, but I believe each project and people will have different contexts and solutions for that, like some people wanting to do that on their CI instead of locally, etc, so this could turn into a quite big paragraph for the README

So *I thing an entry in the Wiki could be more appropriate*. That way people could also easily share their experience and add other solutions they found useful for different use cases for example.

I encourage you to create a simple wiki page [there](https://github.com/AliSoftware/SwiftGen/wiki) (you should have access to edit the wiki I think) and document that (probably with some captures) once you've configured it successfully on your project. That'll be probably as simple as what the Apple documentation I linked above says, but maybe with a screenshot including the script with the swiftgen calls).

I also know that @jschmid is [using it on his CircleCI builds](https://github.com/AliSoftware/SwiftGen/issues/35) to ensure that developers did not forget to regenerate the files if needed. That's a different but interesting approach too, which he may also be interested to help you document in that wiki page.

**Comment by vkaramov** [comment]
I wrote a post about that https://www.linkedin.com/pulse/easy-way-manage-your-storyboards-viacheslav-karamov?trk=prof-post

Hope this will help.

**Comment by ivanbruel** [comment]
Just to provide a quick example for people looking into this (based on how swiftlint does it)

Add a run script phase and paste:
```
if which swiftgen >/dev/null; then
swiftgen storyboards <Project Name> --output <Project Name>/Resources/Storyboards.swift
else
echo "SwiftGen does not exist, download from https://github.com/AliSoftware/SwiftGen"
fi
```

**Comment by jschmid** [comment]
I added a wiki page about [continuous integration](https://github.com/AliSoftware/SwiftGen/wiki/Continuous-Integration).
Feel free to update it !

**Comment by mman** [comment]
Thanks guys for your help,
Martin

**Comment by AliSoftware** [comment]
@jschmid Thx!

@mman Do you think we can close the issue or do you want to wait until you add more info to the wiki page @jschmid started?

**Comment by AliSoftware** [comment]
Note that you can also check what @MrAlek did in #64 to integrate SwiftGen to their Xcode project using a Build Phase like other suggested here; the capture he posted might give you some more pointers.

**Comment by AliSoftware** [comment]
I added a dedicated wiki page [here](https://github.com/AliSoftware/SwiftGen/wiki/Integrate-SwiftGen-in-an-xcodeproj). Feel free to improve it. I'm closing this issue now :wink:
