### ISSUE TITLE
Add View Controller placeholders support

### ISSUE THREAD

**Issue by vkaramov** [AliSoftware/SwiftGen#61]
XCode 7 and iOS 9 supports View Controller placeholders in your storyboards. But swiftgen doesn't support them.

Generated enum looks like this:

enum ServicePromo : String, StoryboardScene {
      case nextSegue = "NextSegue"
      static func nextSegueViewController() -> UIViewControllerPlaceholder 
      {
        return ServicePromo.nextSegue.viewController() as! UIViewControllerPlaceholder
      }
}

**Comment by AliSoftware** [comment]
Care to make a PR? Should be pretty easy to fix the StoryboardParser to detect such nodes I think.

**Comment by vkaramov** [comment]
I guess so, but I'm pretty busy in 2 projects. I'll probably make a PR later this week.

**Comment by AliSoftware** [comment]
Fine by me, I'm busy too so you'll probably beat me to it anyway :wink: :+1:

**Comment by vkaramov** [comment]
Hello, when are you going to merge or reject my PR?
And one more question: why swiftgen crashes when launched from the debugger?

**Comment by AliSoftware** [comment]
Sorry I've been super super busy this month both at work and in personal life and I admit I totally forgot your PR, so thanks for reminding me! I commented on it as I wish that code to be tested before merging anything.

Regarding the debugger, I'm not sure I understand your question. You mean when you try to run the SwiftGen.xcodeproj from Xcode, right? If so, yeah that's an issue with Xcode which is not yet really fit for Command Line projects (= that produce a single binary without a bundle) written in Swift (as projects written in Swift depend on Swift dynamic libs and the Swift dylibs are normally copied by Xcode in the app _bundle_ — inside `YourApp.app/Frameworks` — but for CLI tools there is no bundle). So for CLI apps I mostly use Xcode so that I have syntax highlighting and code completion but building require a custom string.
Hopefully this will change soon with Swift becoming OpenSource and the Swift Package Manager and Apple wanting to make Swift apps working on Linux (which means no bundles but flat binaries and no frameworks or done differently) and a future version of Xcode supporting that.

**Comment by vkaramov** [comment]
Hello,
I've updated unit tests, so please take a look.

**Comment by AliSoftware** [comment]
[Version 0.7.4 release submitted to Homebrew](https://github.com/Homebrew/homebrew/pull/47205) :)

**Comment by vkaramov** [comment]
Great! Thanks!
