### ISSUE TITLE
IBDesignables & string generation in build script causes infinite build loop

### ISSUE THREAD

**Issue by MrAlek** [AliSoftware/SwiftGen#64]
This is a super weird issue I have.

I have an iOS 9 project running on Xcode 7.1.1 using base internationalization. I use Swiftgen 0.7.2 to generate a LocalizedStrings.swift file as a build phase just before the `Compile Sources` phase in my app target. This is what my command looks like:

``` bash
 swiftgen strings --templatePath $SRCROOT/../Swiftgen/strings.stencil --output $SRCROOT/Dooer/Resources/Other-Sources/LocalizedStrings.swift $SRCROOT/Dooer/Resources/Localized/Base.lproj/Localizable.strings
```

Now whenever I open a storyboard in Interface Builder that has an IBDesignable view in it, a build triggers to compile the view, naturally. The problem is that something in SwiftGen makes Xcode trigger a new build to be run as soon as first build completes, creating an infinite loop of builds that only stop when I leave the storyboard. As soon as I disable the SwiftGen command, everything is fine. One build is triggered as I enter the storyboard and that's it.

My initial thought was that maybe Xcode doesn't like `LocalizableStrings.swift` to be overwritten mid-build but even if I let SwiftGen write to a file not in the project, the build loop continues. Nothing in the build log looks strange either.

Appreciate any help. I'll try to replicate the issue in a demo project and upload it if it's not straight forward.

**Comment by AliSoftware** [comment]
Ah, interesting

This is probably because of how Xcode works. When using `IBDesignable`, Xcode has to build the target containing your source files referenced in your XIB/Storyboard with the `IBDesignable` attribute, in order to live-render this view in your XIB.

But indeed I guess that because your script modifies the source contained in that target (in your case `LocalizableStrings.swift`) then the XIB/Storyboard sees that the source changed and re-trigger a build as a result.

This is probably a bug that could be filed to Apple (not necessarily this specific case with SwiftGen, but the fact that if the build process generates files as part of its build, this should not re-trigger a build and lead to infinite look)

I see multiple solutions for your case:

 * The best and fastest one to put in place is probably to specify in your Script Build Phase that it should only be triggered when your `Localizable.strings` file was modified since last build. See [this article](http://indiestack.com/2014/12/speeding-up-custom-script-phases/) that explains how to use the "input files" box of the Script Build Phase to achieve that kind of thing
* You could also separate your custom views (the ones containing `IBDesignable`) in a dedicated framework target. This will have the advantage that Xcode will only rebuild that target when it needs to display your XIB/Storyboard containing `IBDesignables`, one advantage being that the build to display that XIB will be faster than rebuilding the whole app target, another being that `Localizable.strings` will not be part of the target so won't be affected.
* Maybe a last solution (but not sure it won't trigger the same bug, so probably only worth trying if the other two fail) would be to move your script from the Script Build Phase to the Pre-Build Action of you Scheme

HTH.

**Comment by MrAlek** [comment]
Thanks for the quick reply!

I couldn't get the input files trick to stop the script from running but it worked moving the designables to a separate framework.

Even though my problem was solved, I still feel like the underlying issue can and should be solved in SwiftGen. We never know how long it takes Apple to fix a radar (if they even agree it's necessary) and meanwhile, one shouldn't have to restructure their targets within a project just to include a script that generates string constants.

A possible solution would be to check for an existing file and compare its hash checksum before overwriting. That way, if no changes have been made, the file never gets overwritten and Xcode has nothing to complain about. What to you think?

**Comment by AliSoftware** [comment]
I see your point and agree that Xcode might take some time to fix a bug. I still encourage you to file a radar, that I could even dupe if needed.

The input+output files trick should have worked, strange. It already worked for me for other Build Scripts (tough it was for a different usage).

I'm not sure that's the responsibility of SwiftGen to fix that bug. First that's not really SwiftGen's fault, and that's only your usage in a Build Script that cause Xcode to infinite loop, and second I'm sure there exist a dedicated unix utility or something you can pipe to the output of SwiftGen and that takes the content in `stdin` and only write to a file if the content is different.

**Comment by MrAlek** [comment]
Thanks for being detailed with explaining your point of view and providing with alternate solutions to my problem.

I see your point and understand why you wouldn't want to change SwiftGen's behavior because of a specific use case which surfaces what's really a bug in Xcode.

You can close this issue for now. I'll file that radar and see if I can do some bash magic and I'll keep this issue updated.

**Comment by AliSoftware** [comment]
Note that you çan omit the `--output` of SwiftGen so it generates the code to stdout that you can then pipe to your future UNIX utility.

**Comment by MrAlek** [comment]
Toyed around a bit more with the script input / output files and got it to work! Now it only runs when Localizable.strings is modified.

![skarmavbild 2015-11-27 kl 10 02 42](https://cloud.githubusercontent.com/assets/1496135/11437451/229b07da-94ee-11e5-9c12-cd7521367804.png)

Thanks again for helping me out!

**Comment by AliSoftware** [comment]
Great! Out of curiosity, what did you miss the first time you tried that solution?

**Comment by AliSoftware** [comment]
BTW, If you have some time it would be helpful to others to create a page in my wiki to help others know how to configure that kind of stuff properly.

Someone already created [this wiki page](https://github.com/AliSoftware/SwiftGen/wiki/Continuous-Integration) to show how to integrate SwiftGen in a CI server, and some people are asking in #59 how to do what you did, so a wiki page to share your experience might interest a lot of people!

**Comment by MrAlek** [comment]
Hey, sorry for not getting back to you for this long.

I just edited the wiki, adding information regarding this issue and how to solve it.

My problems earlier had to do with not specifying the output file. Seems like you have to specify both input & output even just for the conditional check that input files haven't changed.

**Comment by AliSoftware** [comment]
Perfect thanks!

**Comment by AliSoftware** [comment]
Hey @MrAlek 

The next release of SwiftGen (which will be released very soon, just waiting for a last-minute PR to finish) will include #90, which will theoretically solve your looping issue without relying on `$SCRIPT_INPUT_FILE_x` anymore, by avoiding to write the output file (given thru the `--output` flag) if its content didn't change.

Hope you can test it soon and validate it solves this looping issue once and for all.
Once released and the fix confirmed, I'll probably remove the paragraph in the wiki to avoid confusion.

**Comment by MrAlek** [comment]
Hey! Looks great, quite a minimal code change to get this issue over with.

I'll try it out later this afternoon!

**Comment by MrAlek** [comment]
The PR definitely solved it :+1:

**Comment by AliSoftware** [comment]
Great, thanks for your feedback! :+1:
