### ISSUE TITLE
Add type to StoryboardSceneType.initialViewController

### ISSUE THREAD

**Issue by amarcadet** [AliSoftware/SwiftGen#68]
Hi,

_First, thanks for your time and work, it's a great tool, saved me a lot of time!_

Is it possible to add a type to `StoryboardSceneType.initialViewController`?

It would remove the necessity of adding a Storyboard ID in certain case.

Especially in a case that was causing me an issue: I have a `Loading.storyboard` containing a single controller with a Storyboard ID "loading".
```swift
struct StoryboardScene {
  enum Loading : String, StoryboardSceneType {
    static let storyboardName = "Loading"

    case Loading = "loading"
    static func loadingViewController() -> LoadingViewController {
      return Loading.Loading.viewController() as! LoadingViewController
    }
  }
}
```
This caused the error message `Static member 'Loading' cannot be used on instance of type 'StorybardScene.Loading'`

Note: I'm using release 0.7.3

Thanks

**Comment by AliSoftware** [comment]
Hi @amarcadet 

Adding the return type to `initialViewController` would indeed be a nice enhancement. Could be a great feature to add.

However, I don't see how this is related to your `Static member 'Loading' cannot be used on instance of type 'StoryboardScene.Loading'`` error. Did you mean to file two separate issue, one for the feature request and the other for an actual bug?

**Comment by AliSoftware** [comment]
@amarcadet 

I just fixed the error you had by modifying the default template (you could have done it on your own template — no need to update SwiftGen for that even). That was due to an ambiguity for the compiler because the enum and case had the same name, so I disambiguated it.

Regarding `initialViewController` returning the proper subclass, after thinking about it I'm not sure that's entirely possible. Well it could be, but would require (1) finding the back-reference of the objectID mentioned as being the initialViewController in the storyboard's XML tree (2) more importantly, reimplementing `initialViewController` in each generated `enum` instead of using the protocol's default implementation. You could make a PR if you like to add this feature yourself, but not sure it's worth the effort to do that myself given that last point.

**Comment by amarcadet** [comment]
Thanks for the fix!

Regarding `initialViewController`, I think it would be a nice to have.I will try to take a look and make PR if I succeed.
