### ISSUE TITLE
What's the type of a StoryboardScene enum ? 

### ISSUE THREAD

**Issue by smadbe** [AliSoftware/SwiftGen#74]
First of all, thanks a lot for this tool, I was  waiting for this for 4 years :-)

I have a question, which is not an issue.

I have a classical storyboard scene which is generated by swiftgen:
```
struct StoryboardScene {
  enum Dashboard : StoryboardSceneType {
    static let storyboardName = "Dashboard"
  }
...
```

So to separate the configuration of my tab bar from the rest, I have 
```
  private struct Tab {
    let storyBoardName: StoryboardSceneType
    let logo: UIImage.Asset
    let logoSelected: UIImage.Asset
  }
  
  private let content = [
     Tab(storyBoardName: StoryboardScene.Dashboard, logo: .Home_32px, logoSelected: .Home_32px_Selected),
...
```
This does not work because `StoryboardScene.Dashboard` is of type `StoryboardScene.Dashboard.Type` which does not conform to `StoryboardSceneType` while I have the impression it does. I don't really understand why. And how am I supposed to do such a thing ?

**Comment by AliSoftware** [comment]
Your initializer of `private struct Tab` expect its first parameter to be an instance of type `StoryboardSceneType`. `StoryboardScene.Dashboard` is a type, not an instance of this type.

Depending on what you want to achieve, you might want to:

1. Pass the storyboard name (and not the enum type), as your struct property name actually suggests:

`Tab(storyboardName: StoryboardScene.Dashboard.storyboardName, …)`

2. Or store the type (instead of an instance) in your `struct Tab`:

```
private struct Tab {
  let storyboardType: StoryboardSceneType.Type
  …
}
```
Then you can call `Tab(storyboardType: StoryboardScene.Dashboard, …)` and use it as such a generic `StoryboardSceneType` metatype next.

**Comment by smadbe** [comment]
Thanks for the quick answer. You're right, it is the type of the type, and not the instance. Of course, I do not want to put the name string as the goal of using your tool is to have something failing at compile time.

So following your advise, I have
```
  private struct Tab {
    let storyBoardType: StoryboardSceneType.Type
    ...
  }
  ...
   Tab(storyBoardType: StoryboardScene.Settings, logo: .Sliders_32px, logoSelected: .Sliders_32px_Selected)
```
But this does not work because I cannot just pass a type, I get "Expected member name or constructor call after type name".

So I have to do: 
```
Tab(storyBoardType: StoryboardScene.Settings.self, logo: .Sliders_32px, logoSelected: .Sliders_32px_Selected)
```
and then use later with:
```
s.storyBoardType.initialViewController()
```
Would you have an idea of cleanest (less verbose) way ?

**Comment by AliSoftware** [comment]
No, I think that's the shortest way you can get with Swift for your use case, so your solution is the right one I think.

**Comment by smadbe** [comment]
Ok thanks!
