### ISSUE TITLE
Not able to parse multiple .strings files

### ISSUE THREAD

**Issue by AndrewSB** [AliSoftware/SwiftGen#84]
I've been using swiftgen for a while with one project now, and I've finally noticed that it isn't properly parsing my `.strings` files -- something strange is going on.

I have two currently: `Localizable.strings` and `Contant.strings`
And in my build phase there are these two lines: 
```
/usr/local/bin/swiftgen strings "${PROJECT_DIR}/${PROJECT_NAME}/Supporting Files/Localizable.strings" --enumName "Localizable" --output "${PROJECT_DIR}/${PROJECT_NAME}/Supporting Files/Constants/Localizable_Strings.swift"
/usr/local/bin/swiftgen strings "${PROJECT_DIR}/${PROJECT_NAME}/Supporting Files/Constant.strings" --enumName "Contants" --output "${PROJECT_DIR}/${PROJECT_NAME}/Supporting Files/Constants/Constant_Strings.swift"
```

The generated files (both of them) show all the strings I have in my `.strings` files, with the correct content in the comment above each enum case.

The issue appears at runtime. If I use `tr()` on any of the cases from the generated `Localizable.strings` enum, it works great, but if I try to `tr()` a `Constant.strings` case, it just returns the enum key, instead of the value (for eg. a line which is `"login.facebookreadpermissions" = "email, user_birthday, public_profile, user_friends";`, when evaluated with `tr()` returns the string `login.facebookreadpermissions` instead of the expected value)

Any ideas what could be wrong? I've checked to make sure `Contant.strings` is in the Copy Bundle Resources build phase

**Comment by AliSoftware** [comment]
That's not a problem on your part, but on mine, that's because my implementation of `tr()` in the template use `NSLocalizedString` (and doesn't use the `tableName:` parameter) so it always looks at the string in the default strings file, which is `Localizable.strings`

I recently [added the `tableName` key in the Stencil context](https://github.com/AliSoftware/SwiftGen/blob/master/GenumKit/Stencil/Contexts.swift#L131) which means that theoretically you should [create a custom template](https://github.com/AliSoftware/SwiftGen/blob/master/documentation/Templates.md) based on the default one, but which make use of this `tableName` variable in the template in the `tr` implementation, [instead of using the `NSLocalizedString` without a table name like I do so far](https://github.com/AliSoftware/SwiftGen/blob/master/templates/strings-default.stencil#L30-L38).

This should actually be pretty straightforward to do, so don't hesitate to try it.

If you manage to create a nice template taking that `tableName` into account, don't hesitate to make a PR: I'd gladly add such a template as part of the templates bundled with SwiftGen itself.

**Comment by AliSoftware** [comment]
Also related: #39

**Comment by AndrewSB** [comment]
closing this and moving discussion to PR #86
