### ISSUE TITLE
Build loops when using storyboards

### ISSUE THREAD

**Issue by mathiasnagler** [AliSoftware/SwiftGen#89]
I am using `swiftgen storyboards` in a project that has multiple storyboards. In those storyboards I use multiple `IBDesignable`s and `IBInspectable`s. Unfortunately this seems to cause build loops for me.

There is a wiki page in the `SwiftGen` project, that describes how to prevent build loops by using Xcode's support for custom `Input Files` and `Output Files`. I do not see how this works in my case however.

Using a single `Input File` is not possible as I have multiple storyboards. Using multiple `Input Files` is also impossible currently there is seemingly no support for multiple parameters in `SwiftGen`. I also tried to put all of my Storyboard in an extra folder and specifying this as my `Input File` but it seems as this does not work because Xcode does not correctly detect changes. Thus, the build phase is never executed.

Is there any workaround for my issue besides of disabling `Automatically Refresh Views` in Interface Builder?

**Comment by AliSoftware** [comment]
Hi Mathias,

The normal solution should be to specify as the `Input Files` the directory SwiftGen will scan for storyboards, and as the `Output Files` the file generated by SwiftGen (like `Storyboards.swift` if you used `--output Storyboards.swift`)

According to the documentation but also to [this article](http://indiestack.com/2014/12/speeding-up-custom-script-phases/) — which actually tested using a directory as input "files" — this should normally work. So that's strange that you seem to says that "Xcode does not correctly detect changes" and the build phase is never executed :unamused: 

What you could try if the "directory as input file" solution doesn't work is:

* Either create a Makefile, which have a single target depending on every `*.storyboard` file and run the `swiftgen` command — The Makefile will take care of looking for modifications and only run the command if there is no modification
* Or make a Pull Request to SwiftGen so that `--output` will only write the string to the file if the file content is different, and won't touch the file if it's already the same content. That could actually solve multiple problems at once I guess, so it could be both easy to implement and a good solution for your use case and other's.

**Comment by mathiasnagler** [comment]
Your second suggestion seems like a very sensible approach to me. I will try to make a Pull Request in the next couple of days.

**Comment by AliSoftware** [comment]
Closed via #90
